services:
  - type: web
    name: aira-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free  # or "starter", depending on your Render plan
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false