services:
  - type: worker
    name: aira-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OWNER_ID
        sync: false
